### ISSUE TITLE
Contains method doesn't really work

### ISSUE THREAD

**Issue by mattwright42** [mattwright42/Password-Checker#1]
The Contains() method doesn't really work here because the Codecademy code came with a pre-built tool that checked for the required letters, numbers, and characters. This was more about practicing the workflow.

**Comment by RyanWils** [comment]
Hi I would like to help solve this issue.

**Comment by mattwright42** [comment]
Hi Ryan! Go for it. Let me know if you need anything.

**Comment by RyanWils** [comment]
Hi Matt, 
I added a function to the class to work as a Contain function would work. 
Please give it a try and contact me if anything is wrong
